pipeline {
    agent any
    tools { 
        maven 'maven-3.6.3'
    }
    stages {
        stage ('Initialize') {
            steps {
                    echo "Init"
            }
        }
   
        stage ('Build') {
            steps {
                bat 'mvn clean package'
                echo 'Shir is finishing Building her Project'
            }
      }
      stage ('Run') {
            steps {
                bat 'java -cp helloworld-1.0.jar com.coveros.demo.helloworld.HelloWorld'
                echo 'Shir is finishing Running her Project'
            }
      }      
        
        
        
    }
}
