pipeline {
    agent any
    tools { 
        maven 'maven-3.6.3'
    }
    stages {
        stage ('Initialize') {
            steps {
                    echo "Init"
            }
        }
        stage ('Build') {
            steps {
                bat 'mvn clean package'
                echo 'Shir finished Building her Project'
            }
      }
      stage ('Run') {
            steps {
                bat 'java -jar target/multi-module-application-2.0.0.jar'
                echo 'Shir is finishing Running her Project'  
            }
      }      

        
    }
}
